apiVersion: v1
kind: Service
metadata:
  name: stake-service
spec:
  type: LoadBalancer  # Use LoadBalancer if you need external access
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: stake-service
