apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: LoadBalancer  # Use LoadBalancer if you need external access
  ports:
  - port: 12345
    targetPort: 12345
    protocol: TCP
  selector:
    app: server
