apiVersion: v1
kind: Service
metadata:
  name: swap-service
spec:
  type: LoadBalancer  # Use LoadBalancer if you need external access
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: swap-service
