apiVersion: v1
kind: Service
metadata:
  name: transfer-service
spec:
  type: LoadBalancer  # Use LoadBalancer if you need external access
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
  selector:
    app: transfer-service
