apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-service-deployment
  labels:
    app: transfer-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transfer-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: transfer-service
    spec:
      containers:
      - name: transfer-service
        image: python-distributed-systems-transfer_service:latest  # Replace with your actual image path
        ports:
        - containerPort: 8084
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/mydatabase"
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health  # Adjust if there's a specific health check endpoint
            port: 8084
        livenessProbe:
          httpGet:
            path: /health  # Adjust if there's a specific health check endpoint
            port: 8084
      restartPolicy: Always
