apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  type: LoadBalancer  # Use LoadBalancer if you need external access
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: portfolio-service
