apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service-deployment
  labels:
    app: portfolio-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: portfolio-service
    spec:
      containers:
      - name: portfolio-service
        image: python-distributed-systems-portfolio_service:latest  # Replace with your actual image path
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/mydatabase"
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health  # Adjust if there's a specific health check endpoint
            port: 8081
        livenessProbe:
          httpGet:
            path: /health  # Adjust if there's a specific health check endpoint
            port: 8081
      restartPolicy: Always
